# Generated by Django 2.1.5 on 2019-02-09 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likearound', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='likearound/profiles/default.jpg', upload_to='likearound/profiles/'),
        ),
    ]
