# Generated by Django 2.1.5 on 2019-02-09 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likearound', '0002_auto_20190209_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dislikes',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='likes',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
