# Generated by Django 2.1.5 on 2019-02-09 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likearound', '0003_auto_20190209_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='is_positive',
            field=models.BooleanField(default=True),
        ),
    ]
