# Generated by Django 2.1.5 on 2019-02-11 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likearound', '0004_auto_20190209_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='likearound/profiles/'),
        ),
    ]
