# Generated by Django 2.1.5 on 2019-01-26 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=120, null=True, unique=True, verbose_name='Slug'),
        ),
    ]
