# Generated by Django 2.1.5 on 2019-01-30 09:51

import audiolist.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='unknown', max_length=100)),
                ('published_at', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='unknown', max_length=100, unique=True)),
                ('slug', models.SlugField(default='', editable=False, max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='musician',
            field=models.ForeignKey(blank=True, default=audiolist.models.default_musician, on_delete=django.db.models.deletion.SET_DEFAULT, to='audiolist.Musician'),
        ),
        migrations.AlterUniqueTogether(
            name='album',
            unique_together={('name', 'musician')},
        ),
    ]
