# Generated by Django 2.1.5 on 2019-01-30 13:18

import audiolist.models
from django.db import migrations, models
import django.db.models.deletion
import django_hash_field


class Migration(migrations.Migration):

    dependencies = [
        ('audiolist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('filehash', django_hash_field.HashField(db_index=True, max_length=16, unique=True)),
                ('data', models.FileField(upload_to='audiolist/music/')),
                ('album', models.ForeignKey(blank=True, default=audiolist.models.default_album, on_delete=django.db.models.deletion.SET_DEFAULT, to='audiolist.Album')),
            ],
        ),
    ]
