# Generated by Django 2.1.5 on 2019-01-30 13:58

from django.db import migrations
import django_hash_field


class Migration(migrations.Migration):

    dependencies = [
        ('audiolist', '0002_track'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='filehash',
            field=django_hash_field.HashField(db_index=True, max_length=16),
        ),
    ]
