# Generated by Django 2.1.5 on 2019-01-30 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiolist', '0003_auto_20190130_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('po', 'pop'), ('in', 'indie'), ('ro', 'rock'), ('me', 'metal'), ('al', 'alternative'), ('el', 'electronic'), ('da', 'dance'), ('ra', 'rap'), ('rb', 'rnb'), ('ja', 'jazz'), ('bl', 'blues'), ('re', 'reggae'), ('sk', 'ska'), ('pu', 'punk'), ('cl', 'classical'), ('rt', 'retro'), ('ch', 'chanson'), ('co', 'country'), ('ba', 'bard'), ('so', 'soundtrack'), ('et', 'ethnic'), ('ci', "children's")], max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='track',
            name='genres',
            field=models.ManyToManyField(blank=True, to='audiolist.Genre'),
        ),
    ]
