# Generated by Django 2.1.5 on 2019-01-30 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiolist', '0004_auto_20190130_1404'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(default='', editable=False, max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='track',
            name='tags',
            field=models.ManyToManyField(blank=True, to='audiolist.Tag'),
        ),
    ]
